codecademy_todo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('todo.urls')),
    url(r'^todo/', include('todo.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

todo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'todo.views.home'),
    url(r'^add_task$', 'todo.views.add_task'),
    url(r'^complete_task$', 'todo.views.complete_task'),
    url(r'^uncomplete_task$', 'todo.views.uncomplete_task'),
    url(r'^delete_task$', 'todo.views.delete_task'),
    url(r'^edit_task$', 'todo.views.edit_task'),
    url(r'^login$', 'todo.views.login'),
    url(r'^logout$', 'todo.views.logout'),
    url(r'^register$', 'todo.views.register')
)

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


# Create your models here.
class Task(models.Model):
    description = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)
    owner = models.ForeignKey(User)


# signals
def create_initial_tasks(sender, instance, **kwargs):
    if kwargs['created']:
        task = Task(
            owner=instance,
            description='Hire Daniel (daniel.hosterman@gmail.com) for some work!'
        )
        task.save()

post_save.connect(
    create_initial_tasks,
    sender=User,
    dispatch_uid='create_initial_tasks'
)

todo/forms.py
from django import forms
from django.forms import TextInput
from todo.models import Task


class NewTaskForm(forms.ModelForm):

    class Meta():
        model = Task
        fields = ['description']
        widgets = {
            'description': TextInput(attrs={
                'placeholder': 'Enter new task...',
                'autofocus': True,
                'required': True
                })
        }


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Username', 'required': True})
    )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Password', 'required': True})
    )


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Username', 'required': True})
    )
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'First Name', 'required': True})
    )
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Last Name', 'required': True})
    )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Password', 'required': True})
    )

todo/views.py
from django.shortcuts import render_to_response, redirect
from django.http import HttpResponse
from django.template import RequestContext
from django.core import serializers
from django.contrib.auth import authenticate, login as login_user, \
    logout as logout_user
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import IntegrityError
from .forms import NewTaskForm, LoginForm, RegisterForm
from .models import Task


# Create your views here.
def home(request):
    user = request.user
    if user.is_active:
        tasks = Task.objects.all().order_by('-id')\
            .filter(completed=False, owner=user)
        completed_tasks = Task.objects.all().order_by('-id')\
            .filter(completed=True, owner=user)
    else:
        tasks = None
        completed_tasks = None
    return render_to_response(
        'home.html',
        {
            'new_task_form': NewTaskForm(),
            'login_form': LoginForm(),
            'register_form': RegisterForm(),
            'tasks': tasks,
            'completed_tasks': completed_tasks,
            'user': user
        },
        RequestContext(request)
    )


def add_task(request):
    """ given a request with a decription and a valid user, insert
    a new database record representing a task and return a json object
    representing the newly inserted record """
    user = request.user
    description = request.POST.get('description')
    new_task = Task(owner=user, description=description)
    new_task.save()
    return HttpResponse(serializers.serialize('json', [new_task]))


def complete_task(request):
    """ given a request with a task, set the task to completed in the database
    and return a json object representing the newly updated record """
    task_id = request.POST.get('task_id')
    task = Task.objects.get(pk=task_id)
    task.completed = True
    task.save()
    return HttpResponse(serializers.serialize('json', [task]))


def uncomplete_task(request):
    """ given a request with a task, set the task to not completed in the
    database and return a json object representing the newly updated record """
    task_id = request.POST.get('task_id')
    task = Task.objects.get(pk=task_id)
    task.completed = False
    task.save()
    return HttpResponse(serializers.serialize('json', [task]))


def delete_task(request):
    """ given a request with a task, delete the task """
    task_id = request.POST.get('task_id')
    task = Task.objects.get(pk=task_id)
    task.delete()
    return HttpResponse(serializers.serialize('json', [task]))


def edit_task(request):
    """ given a request with a task, set the task description in the database
     and return a json object representing the newly updated record """
    task_id = request.POST.get('task_id')
    description = request.POST.get('description')
    task = Task.objects.get(pk=task_id)
    task.description = description
    task.save()
    return HttpResponse(serializers.serialize('json', [task]))


def login(request):
    """ given a username and a password, log the user in and return them to the
    todo page """
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None and user.is_active:
        login_user(request, user)
    else:
        messages.add_message(
            request,
            messages.ERROR,
            'User or password are incorrect.'
        )
    return redirect(home)


def logout(request):
    """ logout the user """
    logout_user(request)
    return redirect(home)


def register(request):
    """ register a new user """
    username = request.POST.get('username')
    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')
    password = request.POST.get('password')
    try:
        user = User.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password
        )
        user.save()
        authenticated = authenticate(username=username, password=password)
        login_user(request, authenticated)
    except IntegrityError:
        messages.add_message(
            request,
            messages.ERROR,
            'This user already exists.'
        )
    return redirect(home)

todo/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>Get Things Done!</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    <!-- header -->
    <div class="header">
        <h1>Get Things Done!</h1>
        <div class="logout">
            {% if user.is_active and user.first_name %}
                Welcome back, {{ user.first_name }}! <a href="{% url "todo.views.logout" %}">Logout?</a>
            {% elif user.is_active %}
                Welcome back! <a href="{% url "todo.views.logout" %}">Logout?</a>
            {% endif %}
        </div>
    </div>

    <!-- login -->
    {% if not user.is_active %}
        <div class="login">
            <form action="{% url "todo.views.login" %}" method="post">
                {% csrf_token %}
                {{ login_form }}
                <button name="Login">Login</button> or <button name="Register" type="button">Register</button>
            </form>
            <span class="message">{% for message in messages %} {{ message }} {% endfor %}</span>
        </div>
    {% endif %}

    <!-- register -->
    {% if not user.is_active %}
        <div class="register" style="display: none;">
            <form action="{% url "todo.views.register" %}" method="post">
                {% csrf_token %}
                {{ register_form }}
                <button name="Login">Sign Me Up!</button>
            </form>
            <span class="message">{% for message in messages %} {{ message }} {% endfor %}</span>
        </div>
    {% endif %}

    <!-- add task -->
    <div class="add-task">
        {% if user.is_active %}
            {% csrf_token %}
            {{ new_task_form }}
            <button name="Add Task">Add Task</button>
        {% else %}
            <label for="id_description">Description:</label><input readonly id="id_description" maxlength="200" name="description" placeholder="Enter new task..." type="text">
            <button name="">Add Task</button>
        {% endif %}
    </div>
    

    <!-- todo items -->
    <section class="to-do">
        <h2>To Do</h2>
        {% for task in tasks %}
            <article class="todo-item" data-task-id={{ task.id }}>
                <input type="checkbox">
                <span class="description">{{ task.description }}</span>
                <input type="text" value="{{ task.description }}" style="display: none;">
                <button name="Delete Task"></button>
                <button name="Edit Task"></button>
            </article>
        {% endfor %}

        {% if not user.is_active %}
            <article class="todo-item">
                <input type="checkbox">
                <span class="description">Login to your account or create a new one!</span>
                <input type="text" value="Login to your account or create a new one!" style="display: none;">
                <button name="Delete Task"></button>
                <button name="Edit Task"></button>
            </article>
        {% endif %}
    </section>

    <!-- completed items -->
    <section class="done">
        <h2>Recently Completed Items</h2>
        {% for task in completed_tasks %}
            <article class="done-item" data-task-id={{ task.id }}>
                <input type="checkbox" checked>
                <span class="description">{{ task.description }}</span>
                <input type="text" value="{{ task.description }}" style="display: none;">
                <button name="Delete Task"></button>
                <button name="Edit Task"></button>
            </article>
        {% endfor %}

        {% if not user.is_active %}
            <article class="done-item">
                <input type="checkbox" checked>
                <span class="description">Push this project to Github!</span>
                <input type="text" value="Push this project to Github!" style="display: none;">
                <button name="Delete Task"></button>
                <button name="Edit Task"></button>
            </article>
        {% endif %}
    </section>

    <!-- technology icons -->
    <div class="icons">
        <a href="https://www.djangoproject.com/"><img src="{% static "assets/images/dj.png" %}" alt="Django"></a>
        <a href="http://jquery.com/"><img src="{% static "assets/images/jquery_64_black.png" %}" alt="jQuery"></a>
        <a href="https://github.com/dhosterman/codecademy_todo"><img src="{% static "assets/images/github_64_black.png" %}" alt="Github"></a>
    </div>
</body>
<script src="{% static "bower_components/jquery/dist/jquery.min.js" %}"></script>
<script src="{% static "bower_components/jquery-cookie/jquery.cookie.js" %}"></script>
<script src="{% static "js/script.js" %}"></script>
</html>